### PR TITLE
Users update (something like bugfix) + File manager - new features

### PR DESCRIPTION
**Pull request by Konlab**
Users update- now users api checks for the argument type and more checkings! ~ 30 mins of work
File manager- added pager that is shown only if you have 17< files
User manager - minor bugfix

TESTED-WORKING

### CODE REVIEW

**Comment by FlareHAX0R** [comment]
This won't like, interfere with older programs, right?

**Comment by Konlab** [comment]
Won't interfere

**Comment by Konlab** [comment]
Just more fs.exists and argument var type testing

**Comment by FlareHAX0R** [comment]
I already pushed it.

**Pull request merged**
