### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Konlab**
fileman.exc:
update to version 1.3
some new things
users update:
added 2 new functions/fixed 1 function
users.exc update:
added 1 new button

more info: see the comments in Konlab/deltaOS's develop branch's files

### CODE REVIEW

**Comment by Konlab** [comment]
oops
in fileman.exc there's written "Move function" - that's not done yet

**Comment by Konlab** [comment]
?

**Comment by FlareHAX0R** [comment]
DeltaOS 1.0 is still in beta.

**Comment by Konlab** [comment]
And it means, that I have to push directly?

**Comment by FlareHAX0R** [comment]
No. That means NO pushing to master branch until 1.0 is ready.

**Comment by Konlab** [comment]
But this pull request is requesting pull to develop

**Comment by FlareHAX0R** [comment]
OH... I SEE.

**Comment by Konlab** [comment]
Thanks for merging

**Pull request merged**
