### PR TITLE
pull request

### PR DESCRIPTION
**Pull request by Konlab**
contains:
user's private file manager for User manager
(using users/files)
bugfix that wasn't necessary but I did it cuz I didn't like that "You aren't a root"
now normal non-root users can't create users from user manager

### CODE REVIEW

**Comment by Konlab** [comment]
DON'T MERGE automatically
I see now that i really can't use github -_-

**Comment by Konlab** [comment]
if you agree I gonna put those manually in the develop FlareHAX0R:develop

**Comment by Konlab** [comment]
Oh just forgot
features like "delete, rebame etc." Aren't added yet in file manager

**Comment by FlareHAX0R** [comment]
Ok.

**Pull request merged**
